language: java

notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: TviXKst8mtCWIXfL8K1mzZ92x2URAiKUNvZNjmwlo1lzvAbOk1cU/e0V/XC2JM54ZyIBNAuBTMfpqC9pmIVEYCS6TMOf6+Vbf5FnOepapl+eIF8YxQmxA0Yj7U1vxbzhYzwBBTyJlmjiuR/RG4l1fc8bQcLgXDPhHDGvUEedC8dsGi/bqTFhaJ/ArfLOmiGnnVGlEZxAiaoiqPaVc5ch06KTDfhKoeBdmGdYgzzPYlIsqn54HDvcTVTzyadnupQvJ117E6J9IO0ejgT+cstsgyO/6Ms0Glqto7RG1BnOBZBymvn/jH+0HTF4bW4YTSqcb7VujBSRhNTv1aBBYJ2w8s5YIyVXSOJgbgiQIk8zyyZdQz93Cj/i3un6PXwDU+NNWWdADeyzq0a0Ze7vXpocugDBDNPDDwBAfspZx7VHP1VFZUZbkbqPy144jUsXaxO4ve2uiWXnY7iWhq6SYz/YoMyzwxhb2pvvWiRx+HyxHDzox+k/IamhxT0P8LdUBwDph81T9XyR1RP3yMOI2ZbGgsIGVOtkMmlOuKXHbvkBueKlm94KKLC+3rNv/hrTwIHuSoz6AeK/8RuejeGDm6zNzng1bghxBkbzzVT0y5EN3VOofQ+7AMLds6VZBMTCCdXa520Bx5ILZm5eqbbOMnMs3vMGYhOHvJknb0RmO/3CnVE=
    secure: fXffr2VUQ6mDwgKWvae8sBYwyl0dczwEt1L97I2+2xd1DMxuKtfQUj+sCVzwU8YapqnIq73iA5qM/IIWfSbyixRqbfzVJKBbxp2MF/K5LNhH1pxbZTOe8Mdl1WgexW8zfSU70hfN++b9c1tFsD/QS3Rt+N5onSk6FXf0OdIxbpK7AvQFB6ac1rloHVyTuiBmDPL+PMZ1iAmOixMfkxRGAsoas5kmFwZTeesHp3Oxj9KW+W4WZ143PxsEAh4tLQmzOXe24LD1tClpJhB27Lm/UtNlHjkq0bVwKYwt0M+ZxRbbqCX7T9mh59JGxub+PhmFlIiPHQfirf0CMDu7Qc7cVfIvdzDKBoN3eOHSyoN9igmn7SWO4QqaHtBLth8UlPbXLRLmreZjwe6pSknGgJUHpBf7h5dguRVG/zw4ZjCIPBhlyDnJloURGLkGR0LyItca8Aw2qPei4uvvKiYQRsbUzZ/Df8eZbee8H945p/T7OBk7qednL5JcERF5HyZdYe5zAcuBIdv6aWjVWgc7l6Z7cAPgXOPboaSbKyMwL2xRV/jmauMEFr0CuRKR9tPGZRLABVcmGT47PFCs/iWIO18a3yQnw9JEznuT/kp5qYdUJ7gpdK0Rqp7IqbZijk0nhF95KmWDNMm5lvTmg3JhEi4pnJ2pZuh2zMirXllSYqsw2zk=

sudo: false

jdk:
  - oraclejdk8

branches:
  only:
    - master
script: mvn clean test pmd:check verify
