language: java

notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: YHeiPdluRGuM8fP7ozdsgOydPdg2o8rkMovmMVKm6L2hXMMsDKmk2ua/f2cayOLSG4iT8SLHfoEO2vZ/6t61RVUhywVtz8rlZRiqVsi9o4yzxB8T31m21bf7IIxdeIcpjTGtoxNQv6jrPFUQAfiGHVNXqRRmQnYjX4dutF+ojQ/nbdlxivmsS4zke6fXV/V9VYBMTwllLhVxaNdtg8BpAt7l7VXCrjk1M/3msv3ePbo4gmsDsL3uNQw8qRAfeOK0LXk7BGqyP8Hy0IMakELZgKjfGMbYsPIjpzkc9KYb03QQKegK0JaebkCNN6xRjZ7svhItdD4JwHasM9dHOYDqxwXab6/eWyW2UiGtMXB6loMYJCE8oB1HLpFigOVE7hwTB9CuNRt6b+aOQD2vbqlhP6Tcli5f+tWvHQwCzJayFVmLjXvLEIS+jNnS01UtR5GrSmcVQvbYaIG8LOdWwXsvm5B+VdM6NzxTUZtXfPbetYBvptdaA4P7zBcd2otWEtDF06ES2oU98F++v2ykN7Q+vGN4JqqYEuSoh0tYHX2iaHMsGWzL/giiL626N4BDPt82u8j5cUiGeLTmsQbnHFEgkeHFAVjJAtWa4K+iqtm3ur6APshRGUwRm0Xq8ZVjeymgjALuio+n2oUHqd62xDAwyJjwiH17R6v5QaUsbX0Tc2M=

sudo: false

jdk:
  - oraclejdk8

branches:
  only:
    - master

script:
    - mvn clean test pmd:check verify cobertura:cobertura

before_install:
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
